# Server configuration
server.port=8080
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

# Database connection settings
spring.datasource.url=jdbc:mysql://192.168.1.104:3306/ecommerce
spring.datasource.username=MyDB
spring.datasource.password=Nikitha@23
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Dialect (MySQL 5)
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# Entity scan package (used by HibernateConfiguration)
entitymanager.packagesToScan=com
